# Project Midas Ã¢â‚¬â€ Output Formatter Node
# Author: Atharva Kishor Jadhav (AJ)
# ---------------------------------------------------------------
"""
Formats the agent's output into a final deliverable file.
  - document/vision intent Ã¢â€ â€™ .docx (via python-docx)
  - math intent            Ã¢â€ â€™ .xlsx (via openpyxl)

Also appends the audit log entry (Phase 2 full structured audit).
Attaches a LOW CONFIDENCE warning to the file if is_grounded is False.
"""

import os
import uuid
import logging
from datetime import datetime, timezone
from pathlib import Path
from io import BytesIO
from core.state import MidasState
from core.audit import log_audit_event
from api.stream import publish

try:
    from docx import Document
except ImportError:
    Document = None

try:
    import openpyxl
except ImportError:
    openpyxl = None

try:
    from pptx import Presentation
except ImportError:
    Presentation = None

logger = logging.getLogger(__name__)

OUTPUTS_DIR = Path(os.getenv("OUTPUTS_DIR", "./outputs"))


def _write_docx(content: str, is_grounded: bool, filename: str) -> str:
    doc = Document()
    if not is_grounded:
        # Prepend a visible warning so the operator cannot miss it
        warning_para = doc.add_paragraph()
        run = warning_para.add_run(
            "Ã¢Å¡Â  LOW CONFIDENCE Ã¢â‚¬â€ Output may not be fully grounded in retrieved sources. Verify before use."
        )
        run.bold = True
        run.font.color.rgb = None  # Default to doc theme; can be styled further
        doc.add_paragraph("")

    doc.add_heading("Project Midas Output", 0)
    doc.add_paragraph(content)
    path = OUTPUTS_DIR / filename
    doc.save(str(path))
    return str(path)


def _write_xlsx(content: str, is_grounded: bool, filename: str) -> str:
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Midas Output"

    if not is_grounded:
        ws.cell(row=1, column=1, value="Ã¢Å¡Â  LOW CONFIDENCE Ã¢â‚¬â€ Verify before use.")
        start_row = 2
    else:
        start_row = 1

    # Write content lines as rows
    for i, line in enumerate(content.splitlines()):
        ws.cell(row=start_row + i, column=1, value=line)

    path = OUTPUTS_DIR / filename
    wb.save(str(path))
    return str(path)

def _write_pdf(content: str, is_grounded: bool, filename: str) -> str:
    from fpdf import FPDF
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("helvetica", size=12)
    
    if not is_grounded:
        pdf.set_text_color(255, 0, 0)
        pdf.cell(0, 10, "⚠️ LOW CONFIDENCE — Verify before use.", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(5)
        
    pdf.set_font("helvetica", style="B", size=16)
    pdf.cell(0, 10, "Project Midas Output", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    
    pdf.set_font("helvetica", size=11)
    pdf.multi_cell(0, 8, content)
    
    path = OUTPUTS_DIR / filename
    pdf.output(str(path))
    return str(path)

def generate_pptx(title: str, sections: list[dict]) -> BytesIO:
    prs = Presentation()
    
    # Title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title_shape = slide.shapes.title
    subtitle = slide.placeholders[1]
    title_shape.text = title
    subtitle.text = "Generated by Project Midas"

    # Body slides
    bullet_slide_layout = prs.slide_layouts[1]
    for section in sections:
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]
        
        title_shape.text = section.get("title", "")
        if body_shape.has_text_frame:
            body_shape.text = section.get("content", "")
    
    pptx_io = BytesIO()
    prs.save(pptx_io)
    pptx_io.seek(0)
    return pptx_io


def old_func():
    """
    Post-process LLM output to enforce clean markdown structure.
    This is a deterministic pass Ã¢â‚¬â€ no additional LLM call.
    Rules:
      1. Code blocks must have language tags
      2. Ensure bullet points use consistent hyphen (-) not asterisk (*) or Ã¢â‚¬Â¢
      3. Remove excessive blank lines (max 2 in a row)
      4. Ensure the text doesn't start with whitespace
    """
    import re
    if not text:
        return text

    # 1. Tag untagged code blocks as 'text'
    text = re.sub(r'```\n', '```text\n', text)
    # But don't double-tag already tagged blocks
    text = re.sub(r'```text\n(.*?)```text\n', lambda m: m.group(0).replace('```text\n', '```text\n', 1).replace('```text\n', '```\n', 1), text, flags=re.DOTALL)

    # 2. Normalize bullet points to hyphen
    text = re.sub(r'^[Ã¢â‚¬Â¢Ã¢â€”ÂÃ¢â€“ÂªÃ¢â€“Â¸] ', '- ', text, flags=re.MULTILINE)
    text = re.sub(r'^\* ', '- ', text, flags=re.MULTILINE)

    # 3. Remove excessive blank lines (more than 2 in a row)
    text = re.sub(r'\n{3,}', '\n\n', text)

    # 4. Strip leading/trailing whitespace
    text = text.strip()

    return text


def format_output(state: MidasState) -> MidasState:
    """
    Node: format_output
    Writes the final output file and records the audit log entry.
    """
    task_id = state["task_id"]
    intent = state.get("intent", "document")
    is_grounded = state.get("is_grounded", True)
    content = state.get("execution_result", "").strip()
    start_time = state.get("_start_time", datetime.now(timezone.utc).timestamp())
    prompt = state.get("prompt", "").lower()

    OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
    file_id = str(uuid.uuid4())[:8]
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

    is_presentation = False
    is_pdf = False
    if "pdf" in prompt:
        is_pdf = True
    elif intent in ("document", "vision"):
        if any(kw in prompt for kw in ["slide", "pptx", "presentation"]):
            is_presentation = True

    try:
        if intent == "chat":
            # STANDARD_CHAT generates no file; it's a direct conversational reply.
            output_path = None
            filename = None
            publish(task_id, "result", "Chat response complete.")
        elif state.get("flowchart_path"):
            output_path = state["flowchart_path"]
            filename = Path(output_path).name
            logger.info(f"[{task_id}] Flowchart ready at {output_path}")
            publish(task_id, "result", f"Flowchart ready: {filename}")
        elif not content:
            # The AI script didn't print any text. Check if it created a file itself.
            output_path = None
            recent_files = []
            for f in OUTPUTS_DIR.glob("*"):
                if f.is_file() and "uploads" not in f.parts:
                    if (datetime.now(timezone.utc).timestamp() - f.stat().st_mtime) < 30:
                        recent_files.append(f)
            if recent_files:
                recent_files.sort(key=lambda x: x.stat().st_mtime, reverse=True)
                output_path = str(recent_files[0])
                logger.info(f"[{task_id}] Agent created its own file: {output_path}")
                publish(task_id, "result", f"Agent generated file: {recent_files[0].name}")
            else:
                logger.info(f"[{task_id}] No content printed and no file generated.")
                publish(task_id, "result", "Task executed successfully, but no output was produced.")
        elif is_presentation:
            filename = f"midas_{timestamp}_{file_id}.pptx"
            output_path = OUTPUTS_DIR / filename
            
            title = "Project Midas Output"
            if not is_grounded:
                title += " (⚠️ LOW CONFIDENCE)"
                
            sections = [{"title": "Output", "content": content}]
            
            try:
                pptx_io = generate_pptx(title, sections)
                with open(output_path, "wb") as f:
                    f.write(pptx_io.getvalue())
                
                output_path = str(output_path)
                logger.info(f"[{task_id}] Output written to {output_path}")
                publish(task_id, "result", f"Output file ready: {filename}")
            except Exception as ppt_err:
                logger.warning(f"[{task_id}] PPTX generation failed ({ppt_err}), falling back to DOCX")
                filename = f"midas_{timestamp}_{file_id}.docx"
                output_path = _write_docx(content, is_grounded, filename)
                logger.info(f"[{task_id}] Output written to {output_path}")
                publish(task_id, "result", f"Output file ready: {filename} (fallback)")
        elif is_pdf:
            filename = f"midas_{timestamp}_{file_id}.pdf"
            output_path = _write_pdf(content, is_grounded, filename)
            logger.info(f"[{task_id}] Output written to {output_path}")
            publish(task_id, "result", f"Output file ready: {filename}")
        elif any(kw in prompt for kw in ["file", "document", "docx", "word", "excel", "xlsx", "spreadsheet", "report", "download"]):
            if intent == "math" or "excel" in prompt or "xlsx" in prompt or "spreadsheet" in prompt:
                filename = f"midas_{timestamp}_{file_id}.xlsx"
                output_path = _write_xlsx(content, is_grounded, filename)
                logger.info(f"[{task_id}] Output written to {output_path}")
                publish(task_id, "result", f"Output file ready: {filename}")
            else:
                filename = f"midas_{timestamp}_{file_id}.docx"
                output_path = _write_docx(content, is_grounded, filename)
                logger.info(f"[{task_id}] Output written to {output_path}")
                publish(task_id, "result", f"Output file ready: {filename}")
        else:
            # User didn't ask for a file, just show the text output like Gemini.
            output_path = None
            publish(task_id, "result", "Task executed successfully.")
    except Exception as e:
        logger.error(f"[{task_id}] Failed to write output file: {e}")
        output_path = None
        publish(task_id, "error", f"Output formatting failed: {e}")

    # Audit log Ã¢â‚¬â€ full structured entry (Phase 2 deliverable)
    duration_ms = int((datetime.now(timezone.utc).timestamp() - start_time) * 1000)
    log_audit_event({
        "task_id": task_id,
        "user_id_hash": state.get("user_id_hash", ""),
        "intent": intent,
        "result_type": "success",
        "output_path": output_path,
        "ground_score": state.get("ground_score"),
        "is_grounded": is_grounded,
        "iterations": state.get("iteration", 1),
        "duration_ms": duration_ms,
        "tier_b_dispatched": False,  # Tier A only for all agent-generated code
    })

    return {**state, "final_output_path": output_path}

